### ISSUE TITLE
데이터셋

### ISSUE THREAD

**Issue by BlueDragon20148** [hccho2/Tacotron-Wavenet-Vocoder#6]
혹시 이거 train 시킬 때 기본으로 제공되는 손석희 앵커와 문재인 대통령의 데이터셋으로 하셨나요? train시키려고 보니까 너무 데이터양이 적어서 학습이 잘 될까 궁금해서요.

**Comment by hccho2** [comment]
어느 정도의 data는 확보하셔야 합니다.

**Comment by BlueDragon20148** [comment]
> 어느 정도의 data는 확보하셔야 합니다.

2시간 정도의 데이터는 있는데 충분할까요?
